serenity.project.name = WebServices BDD with Serenity

story.timeout.in.secs=3000

dashboard.tag.list=product,team,layer,release,iteration
report.tagtypes=capability,feature
serenity.requirements.custom.field=Requirements
serenity.use.customfield.releases=true
serenity.release.types=Version,Iteration

report.customfields.environment=QA
report.customfields.soapversion=2.2v
report.customfields.region=Automation
report.customfields.user=Vamsi Krishna
report.customfields.order=environment,soapversion,region,user